spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://host.docker.internal:5432/faang}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD}
    hikari:
      auto-commit: false
      schema: ${DATABASE_SCHEMA:achievement_service}
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DATABASE_SCHEMA:achievement_service}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: ${DATABASE_SCHEMA:achievement_service}
    liquibase-schema: ${DATABASE_SCHEMA:achievement_service}

springdoc:
  swagger-ui:
    enabled:  ${SWAGGERUI_ENABLED:true}
  api-docs:
    enabled: ${API_DOCS_ENABLED:true}        

server:
  port: 8085

logging:
  level:
    root: info
    liquibase: info

user-service:
  host: ${USER_SERVICE_HOST:http://localhost}
  port: ${USER_SERVICE_PORT:8080}
